# Generated by Django 5.1.5 on 2025-01-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_contact_options_alter_news_options_news_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('replied', 'Javob berilgan')], default='new', max_length=255, verbose_name='Status'),
        ),
    ]
