# Generated by Django 5.1.5 on 2025-03-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_tinymceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
